# Generated by Django 4.2 on 2023-05-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab2', '0006_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
