# Generated by Django 4.2 on 2023-05-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab2', '0007_remove_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
